[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["knitting_pattern"]

[project]
name = "knitting_pattern"
version = "0.0.1"
authors = [
  { name="Kaste Ivanauskaite", email="kaste.ivanauskaite@gmail.com" },
]
description = "Kitting pattern calculator tool for my programming course"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Programming-The-Next-Step-2026/knitting_pattern.git"
